language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t lightbulb233/react-test -f ./client/Dockerfile ./client

#script:
#  - docker run -e CI=true jflores233/react-test npm test

deploy:
  - docker build -t lightbulb233/multi-client ./client
  - docker build -t lightbulb233/multi-nginx ./nginx
  - docker build -t lightbulb233/multi-server ./server
  - docker build -t lightbulb233/multi-worker ./worker
  # login to docker hub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #push img to docker hub
  - docker push lightbulb233/multi-client
  - docker push lightbulb233/multi-nginx
  - docker push lightbulb233/multi-server
  - docker push lightbulb233/multi-worker
